# Generated by Django 3.2.4 on 2021-06-29 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(null=True)),
                ('folder_id', models.BigIntegerField(null=True)),
                ('is_folder', models.BigIntegerField(null=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('location', models.CharField(max_length=200, null=True)),
                ('type', models.CharField(max_length=50, null=True)),
                ('last_modified', models.DateField(null=True)),
            ],
        ),
    ]
